### ISSUE TITLE
Disable-PnpDevice: Generic failure (Didn't work)

### ISSUE THREAD

**Issue by n8jadams** [Lulech23/BluePill#2]
I had a couple of bugs when running `BluePill.bat`. One of them is from having Steam big picture loaded I think. Here are some screenshots: 

![failure-screenshot-prompt](https://user-images.githubusercontent.com/24380612/123521538-8b817680-d674-11eb-8248-31ddcddb9477.png)
![failure-screenshot-install](https://user-images.githubusercontent.com/24380612/123521539-8c1a0d00-d674-11eb-80af-8acadaaf1b41.png)
![failure-screenshot-uninstall](https://user-images.githubusercontent.com/24380612/123521540-8c1a0d00-d674-11eb-94fb-56197f46ee9a.png)

**Comment by Lulech23** [comment]
If this fails you can input Win + Ctrl + Shift + B to restart your graphics driver, or restart your PC. Installation most likely still worked. 

There should be a way to refresh the current color profile without restarting the whole graphics driver, but I haven't identified the Windows function for that yet. I'll keep it on the to-do list.

**Comment by Lulech23** [comment]
#4 Windows native calibration loader has been found! Please try v1.2 👍

**Comment by n8jadams** [comment]
So I ran it again (v1.3) There was an error message:

```
ERROR: The system was unable to find the specified registry key or value.
```

Despite this, the color profile changed immediately without manually restarting the graphics driver, and everything seemed to work.

**Comment by Lulech23** [comment]
This is normal on some Windows installations. So long as the profile applied, everything is working!
