### ISSUE TITLE
icc been added but didn't been applied by default

### ISSUE THREAD

**Issue by NOirBRight** [Lulech23/BluePill#3]
After I ran the bat, the icc profile had been added to the system, but the display color didn't change, I had to got into the settings and add th icc file and set it to default to make it work.

**Comment by Lulech23** [comment]
Did the display turn itself off and back on again during setup? My first assumption is that the display driver failed to restart itself, in which case Win + Ctrl + Shift + B would do it. Looking into a better method of applying profiles.

UPDATE: #4 v1.2 has just been released--please try this version and report back with your results.

**Comment by NOirBRight** [comment]
![Uploading IMG_20210629_000205.jpg…]()
tried 1.3 no lucky with it.

**Comment by Lulech23** [comment]
It looks like something went wrong uploading your screenshot. Care to try again?

**Comment by NOirBRight** [comment]
![IMG_20210629_000205](https://user-images.githubusercontent.com/271412/123757457-95afa900-d8f0-11eb-99cc-7cd6281c6ede.jpg)
tried again, failed in the initialization phase.

**Comment by Lulech23** [comment]
Wow, I didn't actually expect anyone to see this error. There is something wrong with your registry beyond what BluePill can fix automatically. As the error message says, you'll have to run display calibration manually first to set a baseline, then run BluePill again.

**Comment by Lulech23** [comment]
Good news: I was able to identify the reason why this is happening for some users, and there is now an update to solve it!

Please try v1.4: https://github.com/Lulech23/BluePill/releases/tag/v1.4
